_BASE_: "./ti_frcnn_baseline_prw_h50.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone_minor"
  ROI_HEADS:
    NAME: "Res5MinorROIHeads"
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: [16, 8]
OUTPUT_DIR: "outputs/tips/prw_tircnn_16x8_m50_re"