_BASE_: "./ti_ddetr_baseline.yaml"
MODEL:
  META_ARCHITECTURE: "DnDabDDETR_Baseline"
  BACKBONE:
    NAME: "build_resnet_backbone_half"
    FREEZE_AT: 2
  RESNETS:
    OUT_FEATURES: ["res3","res4","res5"]
    CHECKPOINT_AT: 4
DETECTOR:
  MODEL:
    IN_FEATS: ["res3","res4","res5"]
    NUM_FEAT_LEVELS: 4
    USE_CHECKPOINT: True  
    D_TRANSFORMER:
      DEC_DEPTH: 6
      DIM_FEEDFORWARD: 2048
      DROPOUT: 0.0
  DN_DETR:
    SCALAR: 5
    LABEL_NOISE_SCALE: 0.2
    BOX_NOISE_SCALE: 0.4
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", ) #
SOLVER:
  MAX_ITER: 34200 # 21361 # 356 * 60+1
  STEPS: (22800,) # (14240,)
  CHECKPOINT_PERIOD: 1140 # 712
  WARMUP_ITERS: 1140 # 712
  IMS_PER_BATCH: 10 # 16
  LR_FACTORS: [0.1,]
  LR_GROUP_REGEX: ["backbone.+",]
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "norm"
    NORM_TYPE: 2.0
    CLIP_VALUE: 0.1
TEST:
  EVAL_PERIOD: 1140 # 712
OUTPUT_DIR: "outputs/tips_next/prw_dndabddetr_4l_h50_6d"