_BASE_: "./ti_ddetr_baseline.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone_half"
    FREEZE_AT: 2
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery", ) #
SOLVER:
  MAX_ITER: 42001 # 700 * 60+1
  STEPS: (28000,)
  CHECKPOINT_PERIOD: 1400
  WARMUP_ITERS: 1400
  IMS_PER_BATCH: 16
TEST:
  EVAL_PERIOD: 1400
OUTPUT_DIR: "outputs/tips_next/cuhk_ddetr_h50"