_BASE_: "./ti_ddetr_baseline.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone_half"
    FREEZE_AT: 2
  RESNETS:
    CHECKPOINT_AT: 4
    OUT_FEATURES: ["res3","res4","res5"]
DETECTOR:
  MODEL:
    IN_FEATS: ["res3","res4","res5"]
    NUM_FEAT_LEVELS: 4
    D_TRANSFORMER:
      USE_CHECKPOINT: True
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery", ) #
SOLVER:
  MAX_ITER: 112051 # 70001 # 700 * 100+1
  STEPS: (89640,) # (56000,)
  CHECKPOINT_PERIOD: 2241 # 1400
  WARMUP_ITERS: 2241 # 1400
  IMS_PER_BATCH: 5 # 16
TEST:
  EVAL_PERIOD: 2241 # 1400
OUTPUT_DIR: "outputs/tips_next/cuhk_ddetr_4l_h50"