_BASE_: "./ti_ddetr_baseline.yaml"
MODEL:
  META_ARCHITECTURE: "DDETR_NextBaseline"
  WEIGHTS: ""
  BACKBONE:
    NAME: "convnext_tiny_minor"
    FREEZE_AT: 1
  CONV_NEXT:
    OUT_FEATURES: ["stage2_unorm","stage3_unorm","stage4_unorm"]
    LAST_STRIDE: False
    PRETRAINED: True
    IN_22K: True
    CHECKPOINT_AT: 3
DETECTOR:
  MODEL:
    IN_FEATS: ["stage2_unorm","stage3_unorm","stage4_unorm"]
    NUM_FEAT_LEVELS: 4
    USE_CHECKPOINT: True  
    D_TRANSFORMER:
      DEC_DEPTH: 6
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", ) #
SOLVER:
  MAX_ITER: 28500 # 21361 # 356 * 60+1
  STEPS: (19000,) # (14240,)
  CHECKPOINT_PERIOD: 950 # 712
  WARMUP_ITERS: 950 # 712
  IMS_PER_BATCH: 12 # 16
TEST:
  EVAL_PERIOD: 950 # 712
OUTPUT_DIR: "outputs/tips_next/prw_ddetr_4l_mnext_6d"