_BASE_: "./ti_ddetr_baseline.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone_half"
    FREEZE_AT: 2
  RESNETS:
    OUT_FEATURES: ["res3","res4","res5"]
DETECTOR:
  MODEL:
    IN_FEATS: ["res3","res4","res5"]
    NUM_FEAT_LEVELS: 4
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", ) #
SOLVER:
  MAX_ITER: 21361 # 356 * 60+1
  STEPS: (14240,)
  CHECKPOINT_PERIOD: 712
  WARMUP_ITERS: 712
  IMS_PER_BATCH: 8
TEST:
  EVAL_PERIOD: 712
OUTPUT_DIR: "outputs/tips_next/prw_ddetr_4l_h50"