_BASE_: "./ti_ddetr_baseline.yaml"
MODEL:
  META_ARCHITECTURE: "DDETR_NextBaseline"
  WEIGHTS: ""
  BACKBONE:
    NAME: "convnext_tiny_minor"
    FREEZE_AT: 1
  CONV_NEXT:
    OUT_FEATURES: ["stage4_unorm"]
    LAST_STRIDE: False
    PRETRAINED: True
    IN_22K: True
    CHECKPOINT_AT: 3
DETECTOR:
  MODEL:
    IN_FEATS: ["stage4_unorm"]
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", ) #
SOLVER:
  MAX_ITER: 21361 # 356 * 60+1
  STEPS: (12104,) #(14240,)
  CHECKPOINT_PERIOD: 712
  WARMUP_ITERS: 712
  IMS_PER_BATCH: 16
TEST:
  EVAL_PERIOD: 712
OUTPUT_DIR: "outputs/tips_next/prw_ddetr_dc5_mnext_step"