_BASE_: "./ti_frcnn_C4Side_prw_llr_16-8.yaml"
MODEL:
  META_ARCHITECTURE: "TiRCNN_C4Joint"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
REID_HEAD:
  POOL_LAYER: "gempoolP"
  TRAIN_WITH_DET: False
  BOX_AUGMENTATION:
    ENABLE: True
    NAME: "dn_detr"
    H_CENTER: 0.4
    H_SCALE: 0.2
    NUM_LABELED: 7
    APPEND_GT: True
    NUM_UNLABLED: 7
SOLVER:
  MAX_ITER: 20538 # 1141 * 30 +1
  STEPS: (13692,) # 
  BASE_LR: 0.003
  IMS_PER_BATCH: 5
  CHECKPOINT_PERIOD: 1141
  WARMUP_ITERS: 1141
TEST:
  EVAL_PERIOD: 2282
OUTPUT_DIR: "outputs/tips/tircnn-c4joint_16-8_prw_1llr_12e_gem_dnboxa_rrr"