_BASE_: "./ti_frcnn_C4Side_prw_llr_16-8.yaml"
MODEL:
  META_ARCHITECTURE: "TiRCNN_C4SideLup"
  WEIGHTS: "outputs/tips/prw_tircnn_16x8/model_final.pth"
REID_HEAD:
  POOL_LAYER: "gempoolP"
  INIT_WEIGHT: "Data/model_zoo/bot_r50-f2-lup_prw_d2.pkl"
  TRAIN_WITH_DET: False
  BOX_AUGMENTATION:
    ENABLE: True
    NAME: "dn_detr"
    H_CENTER: 0.4
    H_SCALE: 0.2
    NUM_LABELED: 9
    APPEND_GT: True
    NUM_UNLABLED: 9
SOLVER:
  MAX_ITER: 34231 # 1141 * 30 +1
  STEPS: (13692,) # 
  BASE_LR: 0.001
  IMS_PER_BATCH: 5
  CHECKPOINT_PERIOD: 1141
  WARMUP_ITERS: 1141
TEST:
  EVAL_PERIOD: 1141
<<<<<<< HEAD
OUTPUT_DIR: "outputs/tips/tircnn-c4side_16-8_prw_1llr_12e_gem_dnboxa-10_botinit-lup"
=======
OUTPUT_DIR: "outputs/tips/tircnn-c4side_16-8_prw_1llr_12e_gem_dnboxa-10_botinit-lup_r"
>>>>>>> c4ed0dc31e8a648441f41686c793b150c62ab77a
