_BASE_: "./ti_frcnn_baseline.yaml"
MODEL:
  META_ARCHITECTURE: "TiRCNN_R34C4Side"
  WEIGHTS: "outputs/tips/prw_tircnn_16x8_r34/model_final.pth"
  RESNETS:
    DEPTH: 34
    OUT_FEATURES: ["res2","res3","res4"]
    RES2_OUT_CHANNELS: 64
  ROI_BOX_HEAD:
      POOLER_RESOLUTION: [16, 8]
REID_HEAD:
  INIT_WEIGHT: "Data/model_zoo/R-34.pkl"
  LOSS:
    OIM:
      LUT_LEN: 483
      QUEUE_LEN: 500
  ROI_POOLER:
    POOLER_RESOLUTION: [16,8]
  PERSON_FEATURE:
    DIM: 512
SOLVER:
  MAX_ITER: 42781 # 1426 * 30+1
  STEPS: (14260,28520)
  CHECKPOINT_PERIOD: 1426
  WARMUP_ITERS: 1426
  BASE_LR: 0.001
  IMS_PER_BATCH: 4
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ( "PRW_Gallery","PRW_InfQ",) #
TEST:
  EVAL_PERIOD: 2852
OUTPUT_DIR: "outputs/tips/tircnn-r34c4side_16-8_prw_llr"