_BASE_: "./ti_frcnn_R34C4Ladder3_cuhk_llr_16-8.yaml"

REID_HEAD:
  TRAIN_WITH_DET: False
  BOX_AUGMENTATION:
    ENABLE: True
    NAME: "dn_detr"
    H_CENTER: 0.4
    H_SCALE: 0.2
    NUM_LABELED: 5
    APPEND_GT: True
    NUM_UNLABLED: 5
SOLVER:
  MAX_ITER: 44833 # 2802 * 16+1
  STEPS: (22416,33624)
  CHECKPOINT_PERIOD: 2802
  WARMUP_ITERS: 2802
  IMS_PER_BATCH: 4
TEST:
  EVAL_PERIOD: 2802
OUTPUT_DIR: "outputs/tips/tircnn-R34C4Ladder3_16-8_cuhk_llr_dnboxa_b4"