_BASE_: "./ti_frcnnfpn_C4Side_cuhk_llr_16-8.yaml"
MODEL:
  WEIGHTS: "outputs/tips/cuhk_tircnnfpn_16x8/model_best.pth"
REID_HEAD:
  POOL_LAYER: "gempoolP"
  TRAIN_WITH_DET: False
  BOX_AUGMENTATION:
    ENABLE: True
    NAME: "dn_detr"
    H_CENTER: 0.4
    H_SCALE: 0.2
    NUM_LABELED: 7
    APPEND_GT: True
    NUM_UNLABLED: 7
SOLVER:
  MAX_ITER: 67261 # 2242 * 30 +1
  STEPS: (22420,)
  BASE_LR: 0.001
  IMS_PER_BATCH: 5
  CHECKPOINT_PERIOD: 2242
  WARMUP_ITERS: 2242
TEST:
  EVAL_PERIOD: 2242
OUTPUT_DIR: "outputs/tips/tircnnfpn-c4side_16-8_cuhk_1llr_10e_gem_dnboxa-8"