_BASE_: "./ti_frcnn_C4Side_prw_llr_16-8.yaml"
MODEL:
  META_ARCHITECTURE: "TiRCNN_C4Coupled"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
REID_HEAD:
  LOSS:
    OIM:
      LB_FACTOR: 10
      ULB_FACTOR: 10
TEST:
  EVAL_PERIOD: 2282
OUTPUT_DIR: "outputs/tips/tircnn-c4coupled_16-8_prw_1llr_12e"