_BASE_: "../tips/frcnn/ti_frcnn_C4Side_prw_llr_16-8.yaml"
MODEL:
  META_ARCHITECTURE: "TiRCNN_2s_CnBaseline"
  WEIGHTS: "outputs/tips/v1/prw_tircnn16_16x8/model_final.pth"
  BACKBONE:
    NAME: "build_resnet_backbone"
  ROI_HEADS:
    NAME: "Res5ROIHeads"
REID_HEAD:
  INIT_WEIGHT: "Data/model_best_prw_cn.pth"
CWS: True
TEST:
  IMS_PER_PROC: 1
OUTPUT_DIR: "outputs/tips_next/2s_frcnn_cn_prw"