_BASE_: "./ti_fcos_baseline.yaml"
MODEL:
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone_half"
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ("PRW_Gallery", ) #
SOLVER:
  MAX_ITER: 12853 # 357 * 36+1
  STEPS: (8568,11781) # 24,33
  CHECKPOINT_PERIOD: 714
  IMS_PER_BATCH: 16
TEST:
  EVAL_PERIOD: 714
OUTPUT_DIR: "outputs/tips/lite_side/prw_fcos_3x_b16_h50"