_BASE_: "./ti_fcos_baseline.yaml"
DATASETS:
  TRAIN: ("CUHK-SYSU_Train",) 
  TEST: ("CUHK-SYSU_Gallery", ) #
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
SOLVER:
  MAX_ITER: 25201 # 700 * 36+1
  STEPS: (16800,23100)
  CHECKPOINT_PERIOD: 1400
  IMS_PER_BATCH: 16
TEST:
  EVAL_PERIOD: 1400
OUTPUT_DIR: "outputs/tips/det/cuhk_fcos_3x_b16_max"