_BASE_: "./ti_ddetr_C4Side_prw.yaml"
MODEL:
  META_ARCHITECTURE: "DDETR_C4SideMmean"
  WEIGHTS: "outputs/tips_next/prw_ddetr_4l_h50_6d/model_0018721.pth"
  RESNETS:
    CHECKPOINT_AT: 6 # disable
OUTPUT_DIR: "outputs/tips_next/lite_tiddetr-c4sidemmean_prw_box5"