_BASE_: "./ti_ddetr_C4Side_prw.yaml"
MODEL:
  META_ARCHITECTURE: "TiDDETR_JointDc_C4Side2StreamOnCropsOimProtoConReFlip"
  WEIGHTS: ""
SOLVER:
  OPTIM: AdamW
  MAX_ITER: 68461 
  STEPS: (44840,) 
  BASE_LR: 1.0e-4
  IMS_PER_BATCH: 5
  CHECKPOINT_PERIOD: 1141
  WARMUP_ITERS: 1141
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "norm"
    NORM_TYPE: 2.0
    CLIP_VALUE: 1.0
TEST:
  EVAL_PERIOD: 1141
OUTPUT_DIR: "outputs/tips_next/lite_tijd_tiddetr-c4side2streamOnCropOimProtoConReFlip_prw_clip1"