_BASE_: "./ti_ddetr_C4Side_prw.yaml"
MODEL:
  META_ARCHITECTURE: "TiDDETR_C4Side2StreamOnCropsS2Infer"
  WEIGHTS: "outputs/tips_next/prw_ddetr_4l_h50_6d/model_0018721.pth"
TEST:
  IMS_PER_PROC: 4
OUTPUT_DIR: "outputs/tips_next/lite_tiddetr-c4side2streamOnCropOimProtoConReFlip_prw"