_BASE_: "./ti_ddetr_C4Side_prw.yaml"
MODEL:
  META_ARCHITECTURE: "TiDDETR_NextC4Side2StreamOnCropsOimProtoConReFlip"
  WEIGHTS: "outputs/tips_next/prw_ddetr_4l_mnext_6d/model_0026599.pth"
  BACKBONE:
    NAME: "convnext_tiny_minor"
    FREEZE_AT: 1
  CONV_NEXT:
    OUT_FEATURES: ["stage1_unorm","stage2_unorm","stage3_unorm","stage4_unorm"]
    LAST_STRIDE: False
    PRETRAINED: True
    IN_22K: True
    CHECKPOINT_AT: 3
DETECTOR:
  MODEL:
    IN_FEATS: ["stage2_unorm","stage3_unorm","stage4_unorm"]
    NUM_FEAT_LEVELS: 4
    USE_CHECKPOINT: True  
    D_TRANSFORMER:
      DEC_DEPTH: 6
REID_HEAD:
  INIT_WEIGHT: ""
  PERSON_FEATURE:
    DIM: 768
SOLVER:
  OPTIM: SGD
  MAX_ITER: 34231 # 1141 * 30 +1
  STEPS: (11410,) #(13692,) # 
OUTPUT_DIR: "outputs/tips_next/minor_tiddetr-nextc4side2streamOnCropOimProtoConReFlip_prw"