_BASE_: "../../../ti_frcnn_baseline.yaml"
MODEL:
  META_ARCHITECTURE: "TiRCNN_C4Side"
  WEIGHTS: "outputs/tips/prw_tircnn/model_final.pth"
  RESNETS:
    OUT_FEATURES: ["res2","res3","res4"]
REID_HEAD:
  INIT_WEIGHT: "Data/model_zoo/tvR-50.pkl"
  LOSS:
    OIM:
      LUT_LEN: 483
      QUEUE_LEN: 500
SOLVER:
  MAX_ITER: 42781 # 1426 * 30+1
  STEPS: (14260,28520)
  CHECKPOINT_PERIOD: 1426
  WARMUP_ITERS: 1426
  BASE_LR: 0.0003
  IMS_PER_BATCH: 4
DATASETS:
  TRAIN: ("PRW_Train",) 
  TEST: ( "PRW_Gallery","PRW_InfQ",) #
TEST:
  EVAL_PERIOD: 2852
CWS: False
OUTPUT_DIR: "outputs/tips/tircnn-c4side_24-12_prw"