_BASE_: "./ti_frcnn_C4Side_cuhk_llr_16-8.yaml"
MODEL:
  META_ARCHITECTURE: "TiRCNN_C4Side_JointDc"
  # NOTE: to avoid resume optimizer
  WEIGHTS: "outputs/tips/lite_side/lite_tijdrcnn-c4side_16-8_cuhk_1llr_10e_gem_dnboxa-8_mdetlr/model_0022419.pth"
  BACKBONE:
    NAME: "build_resnet_backbone_half"
    FREEZE_AT: 2
  ROI_HEADS:
    NAME: "Res5HalfROIHeadsCkpt"
    IOU_THRESHOLDS: [0.5,]
    IOU_LABELS: [0, 1]
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 1.0
REID_HEAD:
  POOL_LAYER: "gempoolP"
  TRAIN_WITH_DET: False
  USE_CHECKPOINT: True
  BOX_AUGMENTATION:
    ENABLE: True
    NAME: "dn_detr"
    H_CENTER: 0.4
    H_SCALE: 0.2
    NUM_LABELED: 7
    APPEND_GT: True
    NUM_UNLABLED: 7
CWS: True
SOLVER:
  MAX_ITER: 44840 # 2242 * (10+20) +1
  STEPS: (35872,) # (10+16)
  BASE_LR: 0.0001
  IMS_PER_BATCH: 5
  CHECKPOINT_PERIOD: 2242
  WARMUP_ITERS: 0
  LR_FACTORS: [30.0,30.0,30.0] # NOTE: start from previous decay checkpoint
  LR_GROUP_REGEX: ["backbone.+","proposal_generator.+","roi_heads.+"]
TEST:
  EVAL_PERIOD: 2242
OUTPUT_DIR: "outputs/tips/lite_side/lite_tijdrcnn-c4side_16-8_cuhk_1llr_10e_gem_dnboxa-8_mdetlr_2nd_detnodrop"