_BASE_: "./ti_frcnn_C4Side_prw_llr_16-8.yaml"
MODEL:
  META_ARCHITECTURE: "TiRCNN_C4Side_JointDc"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_backbone_half"
    FREEZE_AT: 2
  ROI_HEADS:
    NAME: "Res5HalfROIHeadsCkpt"
    IOU_THRESHOLDS: [0.5,]
    IOU_LABELS: [0, 1]
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 1.0
REID_HEAD:
  POOL_LAYER: "gempoolP"
  TRAIN_WITH_DET: False
  BOX_AUGMENTATION:
    ENABLE: True
    NAME: "dn_detr"
    H_CENTER: 0.4
    H_SCALE: 0.2
    NUM_LABELED: 9
    APPEND_GT: True
    NUM_UNLABLED: 9
CWS: True
SOLVER:
  MAX_ITER: 34231 # 1141 * 30 +1
  STEPS: (13692,) # 
  BASE_LR: 0.001
  IMS_PER_BATCH: 5
  CHECKPOINT_PERIOD: 1141
  WARMUP_ITERS: 1141
  LR_FACTORS: [3.0,3.0,3.0]
  LR_GROUP_REGEX: ["backbone.+","proposal_generator.+","roi_heads.+"]
TEST:
  EVAL_PERIOD: 1141
OUTPUT_DIR: "outputs/tips/lite_side/lite_tijdrcnn-c4side_16-8_prw_1llr_12e_gem_dnboxa-10_mdetlr"