MODEL:
  META_ARCHITECTURE: "TiRetina_Baseline"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
    FREEZE_AT: 2
  RESNETS:
    DEPTH: 50
    NORM: "FrozenBN"
    RES2_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2","res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    SMOOTH_L1_LOSS_BETA: 0.0
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.05
    TOPK_CANDIDATES_TEST: 1000
    NMS_THRESH_TEST: 0.5
CWS: False
APK_DROP_LAST: False
REID_HEAD:
  ROI_POOLER:
    TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: [24,12]
    SAMP_RATIO: 2
    SCALES: [0.0625] # 1/16
  POOL_LAYER: "avgpool"
  PERSON_FEATURE:
    DIM: 2048
  TRAIN_REID: True
  TRAIN_WITH_DET: True
  TRAIN_WITH_NMS: True
  USE_CHECKPOINT: False
  ID_ASSIGN:
    NAME: "siou"
    POS_IOU: 0.5
    POS_SCORE: 0.5
  BOX_AUGMENTATION:
    ENABLE: False
  LOSS:
    NAME: "oim"
    OIM:
      NORMALIZE: True
      LB_LAYER: "lb_norm"
      ULB_LAYER: "ulb_full"
      LUT_LEN: 1
      QUEUE_LEN: 1
      LB_FACTOR: 30
      ULB_FACTOR: 30
      SYNC: False
      ADA_MM: "null" # "assign", "obj"
      MM_FACTOR: 0.3
      FOCAL:
        USE_FOCAL: True
        FOCAL_ALPHA: 1
        FOCAL_GAMMA: 2
    LOSS_WEIGHTS:
      OIM: 1.0
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 900)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 900
  MAX_SIZE_TEST: 1500
  FORMAT: "RGB"
  SIZE_DIVISIBILITY: 32

DATALOADER:
  NUM_WORKERS: 8

SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  BASE_LR: 0.01
  WEIGHT_DECAY: 1.0e-4
  GAMMA: 0.1
  IMS_PER_BATCH: 8

TEST:
  IMS_PER_PROC: 8
  DETECTIONS_PER_IMAGE: 100
# SEED: 42
VIS_PERIOD: 500
VERSION: 2
